service: mutant-dna-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 256
  timeout: 30

functions:
  app:
    handler: src/lambda.handler
    events:
      - http:
        path: /api/{proxi+}
        method: ANY
        cors: true
    environment:
      MONGODB_URI: ${env:MONGODB_URI}
      MODE_ENV: ${env:NODE_ENV}